version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  build-and-push-cms:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          repo: swe-project-cms
          path: ~/project/cms
          tag: latest,$CIRCLE_SHA1
  build-and-push-client:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          repo: swe-project-client
          path: ~/project/client
          tag: latest,$CIRCLE_SHA1
  deploy:
    executor: base
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1f:76:d2:e6:25:23:cc:b5:f6:96:ff:d8:ea:52:c4:9c"
      - run:
          name: Run deploy script
          command: bash ~/project/scripts/deploy.sh

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-cms:
          context:
            - swe-project
          filters:
            branches:
              only:
                - main
      - build-and-push-client:
          context:
            - swe-project
          filters:
            branches:
              only:
                - main      
      - deploy:
          context:
            - swe-project
          filters:
            branches:
              only:
                - main
          requires:
            - build-and-push-cms
            - build-and-push-client